version: '3'
services:
  collector:
    build: .
    ports:
      - 3032:8000
    environment:
      - PORT=8000
      - KUBECONFIG=~/.kube/config
    volumes:
      - "./tmp/KUBECONFIG.yml:/root/.kube/config"