apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: dataplattform
  name: ingress-collector
  namespace: dataplattform
spec:
  accessPolicy:
    outbound:
      external:
      - host: nav-dev-kafka-nav-dev.aivencloud.com
        ports:
        - name: kafkassl
          port: 26484
          protocol: TLS
  image: navikt/ingress-collector:v15
  port: 8000
  prometheus:
    enabled: false
    path: /metrics
  istio:
    enabled: false
  liveness:
    path: /is-alive
    timeout: 2
    initialDelay: 2
    periodSeconds: 7
    failureThreshold: 3
  readiness:
    path: /is-ready
    timeout: 2
    initialDelay: 2
    periodSeconds: 7
    failureThreshold: 3
  kafka:
    pool: nav-dev
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  webproxy: true
  env:
    - name: WEB_CONCURRENCY
      value: "1"
    - name: ACCESS_LOG
      value: ""
    - name: REQUESTS_CA_BUNDLE
      value: /etc/pki/tls/certs/ca-bundle.crt
    - name: SSL_CERT_FILE
      value: /etc/pki/tls/certs/ca-bundle.crt
