apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: dataplattform
  name: ingress-collector
  namespace: dataplattform
spec:
  image: {{ image }}
  port: 8000
  prometheus:
    enabled: false
    path: /metrics
  kafka:
    pool: nav-infrastructure
  istio:
    enabled: false
  liveness:
    path: /is-alive
    timeout: 2
    initialDelay: 2
    periodSeconds: 7
    failureThreshold: 3
  readiness:
    path: /is-ready
    timeout: 2
    initialDelay: 2
    periodSeconds: 7
    failureThreshold: 3
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  env:
    - name: WEB_CONCURRENCY
      value: "1"
    - name: ACCESS_LOG
      value: ""
    - name: REQUESTS_CA_BUNDLE
      value: /etc/pki/tls/certs/ca-bundle.crt
    - name: SSL_CERT_FILE
      value: /etc/pki/tls/certs/ca-bundle.crt
    - name: KAFKA_TOPIC
      value: dataplattform.ingress-topic-v2
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-collector-apiserver
  namespace: dataplattform
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 172.16.0.2/32
  podSelector:
    matchLabels:
      app: ingress-collector
  policyTypes:
  - Egress
