apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ingress-topic-v2
  namespace: dataplattform
  labels:
    team: dataplattform
spec:
  pool: nav-infrastructure
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: compact  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 72
  acl:
    - team: dataplattform
      application: ingress-collector
      access: write
    - team: dataplattform
      application: amplitude-proxy
      access: read
    - team: dataplattform
      application: dekoratoren-bigquery
      access: read
    - team: dataplattform
      application: dakan-ingress-indexer
      access: read
