name: Deploy

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.sha }}

on:
  push:
    branches:
      - master
  release:
    types: published

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install requirements
        run: pip install --no-cache-dir -r requirements.txt
      - name: Run unittests
        run: python -m pytest

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . --pull --tag ${IMAGE}
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
          docker push ${IMAGE}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name != 'release'
    strategy:
      matrix:
        cluster: ["dev-sbs", "dev-gcp", "dev-fss"]
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: naiserator.yml, network_policy.yml
          VARS: .nais/${{ matrix.cluster }}.json

  deploy-topic-dev:
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/master' && github.event_name != 'release'
      timeout-minutes: 2
      steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Deploy to dev-gcp
          uses: nais/deploy/actions/deploy@master
          env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
            CLUSTER: dev-gcp
            RESOURCE: topic.yml
            VARS: .nais/dev-gcp.json
