name: Deploy

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.sha }}

on:
  push:
    branches:
      - master
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . --pull --tag ${IMAGE}
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
          docker push ${IMAGE}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name != 'release'
    strategy:
      matrix:
        cluster: ["dev-sbs", "dev-fss", "dev-gcp"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    strategy:
      matrix:
        cluster: ["prod-sbs", "prod-fss", "prod-gcp"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/nais.yaml,.nais/topic.yaml
