name: Deploy

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.sha }}

on:
  push:
    branches:
      - master
  release:
    types: published

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set Python version 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2
      - name: Set Poetry config
        run: poetry config virtualenvs.in-project true
      - name: Install lib
        run: poetry install
      - name: Run unittests
        run: poetry run pytest

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . --pull --tag ${IMAGE}
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin https://docker.pkg.github.com
          docker push ${IMAGE}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name != 'release'
    strategy:
      matrix:
        cluster: ["dev-sbs", "dev-gcp", "dev-fss", "labs-gcp"]
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: naiserator.yml,network_policy.yml
          VARS: .nais/${{ matrix.cluster }}.json

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    strategy:
      matrix:
        cluster: ["prod-sbs", "prod-gcp", "prod-fss"]
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Deploy to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: naiserator.yml,network_policy.yml
          VARS: .nais/${{ matrix.cluster }}.json
